#!/usr/bin/env bash
# ==============================================================================
# install_hooks.sh - Installs local Git pre-commit hooks for Robithoh App
# ==============================================================================
# Sets up .git/hooks/pre-commit to automatically execute:
#   1. Markdown asset validation
#   2. Hardcoded strings linter
#   3. Fast unit test verification (:shared:allTests)
#
# Usage:
#   bash .agents/tools/install_hooks.sh
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

HOOK_FILE=".git/hooks/pre-commit"

echo "========================================================"
echo "⚓ Installing Git Pre-Commit Hook for Robithoh App..."
echo "========================================================"

if [ ! -d ".git" ]; then
    echo "❌ Error: Not a git repository or .git directory missing."
    exit 1
fi

mkdir -p .git/hooks

cat << 'EOF' > "$HOOK_FILE"
#!/usr/bin/env bash
# Git pre-commit hook auto-generated by .agents/tools/install_hooks.sh
set -e

echo "🚀 Running Robithoh Pre-Commit Verification..."

# 1. Validate MVI Architecture & UI Separation
bash .agents/tools/check_mvi_architecture.sh

# 2. Check Sacred Text SHA-256 Integrity
bash .agents/tools/check_sacred_texts.sh

# 3. Validate Markdown Assets
bash .agents/tools/check_markdown_assets.sh

# 4. Check for new hardcoded UI strings
bash .agents/tools/check_hardcoded_strings.sh

# 5. Run fast unit tests
bash .agents/tools/verify_build.sh --fast

echo "✅ Pre-commit verification passed successfully!"
EOF

chmod +x "$HOOK_FILE"

echo "========================================================"
echo "✅ Git pre-commit hook installed successfully at $HOOK_FILE"
echo "========================================================"
